#!/bin/bash

staged_php_files=$( git diff --diff-filter=d --staged --name-only | grep -E '/*\.php$' )
if [ ! -z "$staged_php_files" ]
	then
	npm run lint:php $staged_php_files
	if [ $? != 0 ]
		then
		exit 1
	fi
fi

staged_js_files=$( git diff --diff-filter=d --staged --name-only | grep -E '^js\/\S*\.js$' )
if [ ! -z "$staged_js_files" ]
	then
	npm run lint:js:files $staged_js_files
	if [ $? != 0 ]
		then
		exit 1
	fi
fi

staged_scss_files=$( git diff --diff-filter=d --staged --name-only | grep -E '/*\.scss$' )
if [ -n "$staged_scss_files" ]
	then
	npm run lint:css:files $staged_scss_files
	if [ $? != 0 ]
		then
		exit 1
	fi
fi

if [ -n "$( git diff --diff-filter=d --staged --name-only | grep -E 'package.json' )" ]
	then
	npm run lint:pkg-json
fi
