#!/bin/bash

staged_php_files=$(git diff --diff-filter=d --staged --name-only | grep -E '/*\.php$')
if [ -n "$staged_php_files" ]
	then
	linting="$(npm run lint:php "$staged_php_files")"
	if [ "$linting" ]
		then
		echo "$linting"
		exit 1
	fi
fi

staged_js_files=$(git diff --diff-filter=d --staged --name-only | grep -E '^js\/\S*\.js$')
if [ -n "$staged_js_files" ]
	then
	linting="$(npm run lint:js:files "$staged_js_files")"
	if [ "$linting" ]
		then
		echo "$linting"
		exit 1
	fi
fi

staged_scss_files=$(git diff --diff-filter=d --staged --name-only | grep -E '/*\.scss$')
if [ -n "$staged_scss_files" ]
	then
	linting="$(npm run lint:css:files "$staged_scss_files")"
	if [ "$linting" ]
		then
		echo "$linting"
		exit 1
	fi
fi

if git diff --diff-filter=d --staged --name-only | grep -E 'package.json'
	then
	npm run lint:pkg-json
fi
